### ISSUE TITLE
Compose non-parsed colors

### ISSUE THREAD

**Issue by dy** [colorjs/color-composite#2]
Hi @jamen! Very nice to see your contribution!

How about letting any color input be composed? It feels natural to pass color as a string:
```js
let color = compose(['rgba(255,0,0,.4)', 'rgba(0,255,0,.8)', 'gray'])
//color === 'rgba(...composed values...)'
```
That interface would be similar to [color-interpolate](https://github.com/colorjs/color-interpolate)

**Comment by jamen** [comment]
I did go that way at first when starting the module because it does feel more natural.. but I couldn't decide.

having it take in and return the objects seems better in a chain of operations compared to parse, stringify, parse, stringify, etc.  So I took the approach that the user could `color-stringify` the output if they want, and did the same thing with params.

Your call though.  I would be fine with this usage.  Not sure if the performance is any real concern either, just my train of thought.

**Comment by dy** [comment]
I see. Well it is not necessary to parse/stringify, we could just check if passed color object has `.space` property (that is incredibly fast) and parse it otherwise to get natural interface. As for the returning result - probably we can keep `{space, values}` notation to let user stringify manually.

As for non-rgb mixing we can use `compose(list, space = 'rgb')` notation what do you think?

**Comment by jamen** [comment]
okay sounds good.

for the mixing yes, but I was going to make it default to the first item in `list`'s space.

**Comment by dy** [comment]
> make it default to the first item in list's space

The point is that `hsl` mixing turns out to be significantly different from `rgb` one, because it walks distance by rotating the hue, giving rainbow-like effect. That way if we detect mixing mode from the first argument, accidental passing `hsl(...)` instead of `rgb(...)` would break usual mixing and would puzzle the author.
I would stick to default `rgb` mixing value.
